### ISSUE TITLE
Can't catch exception

### ISSUE THREAD

**Issue by soichih** [TritonDataCenter/node-sshpk-agent#24]
Hello.

Our app is crashing with this exception

```
2021-01-14T17:43:04.006Z [amaretti] error: uncaughtException: Error while connecting to socket: /tmp/0.11251921150910493.0.5478394110224416.0.9537569972344819.ssh-agent.sock: connect ENOENT /tmp/0.11251921150910493.0.5478394110224416.0.9537569972344819.ssh-agent.sock
VError: Error while connecting to socket: /tmp/0.11251921150910493.0.5478394110224416.0.9537569972344819.ssh-agent.sock: connect ENOENT /tmp/0.11251921150910493.0.5478394110224416.0.9537569972344819.ssh-agent.sock
    at Socket.<anonymous> (/app/node_modules/sshpk-agent/lib/client-fsm.js:291:25)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I am trying to find a way to properly handle this condition, but it looks like the exception is thrown inside a nested callback and I can't seem to simply wrap the code with try/catch.. For example, the following doesn't work.

```
try {
    let client = new sshagent.Client({socketPath: auth_sock});
    client.addKey(key, err=>{
        cb(err, agent, client, auth_sock, key);
    });
} catch (err) {
    cb(err);
}
```

When the error occurs, the catch() block will never gets called. Is there a way to prevent sshpk-agent from crashing?

**Comment by arekinath** [comment]
Have you tried adding a `.on('error', ...)` callback to the `client` object in your example? The callback you provide to `addKey()` is only going to receive errors which are specifically related to that command, not general errors like this (which are emitted as eventemitter events on the client object instead).

**Comment by soichih** [comment]
Thanks. I will try that.
